version: 2.1

jobs:
  build_scala:
    docker:
      - image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6

    steps:
      - checkout

      - run:
          name: Run tests
          command: sbt test

workflows:
  version: 2
  build:
    jobs:
      - build_scala:
          filters:
            branches:
              only:
                - feature/scala